directories:
        BINARIES: binaries
        REFERENCES: ../MORA-data/ecoli_data/ecoli.fna
        SAMPLES_DIR: ../MORA-data/ecoli_data/samples
        RESULTS: ecoli_tutorial
        INDEX: index/ecoli_pufferfish
parameters:
        FILES_EXT: .fq.gz
        MAPPING_MODE: pufferfish
        STRATEGY: PE
        TYPE: DNA
        MIN_CNT: 0.1
        MAX_SCORE_DIFFERENCE: 20.0
        SEGMENT_SIZE: 100
        ABUNDANCE_OUTPUT: True
        TAXONOMY: False
        FINAL_ASSIGNMENT_METHOD: "none"
resources:
        MEM_MB: 100000
        TPS: 8
